Exception in thread Thread-87309:
Traceback (most recent call last):
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/cmd.py", line 114, in pump_stream
    handler(line)
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/diff.py", line 570, in <lambda>
    handle_process_output(proc, lambda byt: cls._handle_diff_line(byt, repo, index),
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/diff.py", line 517, in _handle_diff_line
    old_mode, new_mode, a_blob_id, b_blob_id, _change_type = meta.split(None, 4)
ValueError: not enough values to unpack (expected 5, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/cmd.py", line 120, in pump_stream
    raise CommandError([f'<{name}-pump>'] + remove_password_if_present(cmdline), ex) from ex
git.exc.CommandError: Cmd('<stdout-pump>') failed due to: ValueError('not enough values to unpack (expected 5, got 1)')
  cmdline: <stdout-pump> git diff-tree a9f921d7d131ce5778ea5847dc2415c1ea92040e 33ddd522d7fbf21db1f4ce5070b07c6e23e2d2f7 -r --abbrev=40 --full-index -M --raw -z --no-color
Exception in thread Thread-87311:
Traceback (most recent call last):
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/cmd.py", line 114, in pump_stream
    handler(line)
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/diff.py", line 570, in <lambda>
    handle_process_output(proc, lambda byt: cls._handle_diff_line(byt, repo, index),
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/diff.py", line 517, in _handle_diff_line
    old_mode, new_mode, a_blob_id, b_blob_id, _change_type = meta.split(None, 4)
ValueError: not enough values to unpack (expected 5, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/cmd.py", line 120, in pump_stream
    raise CommandError([f'<{name}-pump>'] + remove_password_if_present(cmdline), ex) from ex
git.exc.CommandError: Cmd('<stdout-pump>') failed due to: ValueError('not enough values to unpack (expected 5, got 1)')
  cmdline: <stdout-pump> git diff-tree a9f921d7d131ce5778ea5847dc2415c1ea92040e 33ddd522d7fbf21db1f4ce5070b07c6e23e2d2f7 -r --abbrev=40 --full-index -M --raw -z --no-color
Exception in thread Thread-87313:
Traceback (most recent call last):
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/cmd.py", line 114, in pump_stream
    handler(line)
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/diff.py", line 570, in <lambda>
    handle_process_output(proc, lambda byt: cls._handle_diff_line(byt, repo, index),
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/diff.py", line 517, in _handle_diff_line
    old_mode, new_mode, a_blob_id, b_blob_id, _change_type = meta.split(None, 4)
ValueError: not enough values to unpack (expected 5, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/cmd.py", line 120, in pump_stream
    raise CommandError([f'<{name}-pump>'] + remove_password_if_present(cmdline), ex) from ex
git.exc.CommandError: Cmd('<stdout-pump>') failed due to: ValueError('not enough values to unpack (expected 5, got 1)')
  cmdline: <stdout-pump> git diff-tree a9f921d7d131ce5778ea5847dc2415c1ea92040e 33ddd522d7fbf21db1f4ce5070b07c6e23e2d2f7 -r --abbrev=40 --full-index -M --raw -z --no-color
Exception in thread Thread-87943:
Traceback (most recent call last):
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/cmd.py", line 114, in pump_stream
    handler(line)
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/diff.py", line 570, in <lambda>
    handle_process_output(proc, lambda byt: cls._handle_diff_line(byt, repo, index),
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/diff.py", line 517, in _handle_diff_line
    old_mode, new_mode, a_blob_id, b_blob_id, _change_type = meta.split(None, 4)
ValueError: not enough values to unpack (expected 5, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/cmd.py", line 120, in pump_stream
    raise CommandError([f'<{name}-pump>'] + remove_password_if_present(cmdline), ex) from ex
git.exc.CommandError: Cmd('<stdout-pump>') failed due to: ValueError('not enough values to unpack (expected 5, got 1)')
  cmdline: <stdout-pump> git diff-tree 528f1acd1af3b89853f50515c473167dc230d158 24125ba098550d3f1e7256a8cc536fd325d1ba20 -r --abbrev=40 --full-index -M --raw -z --no-color
Exception in thread Thread-87945:
Traceback (most recent call last):
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/cmd.py", line 114, in pump_stream
    handler(line)
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/diff.py", line 570, in <lambda>
    handle_process_output(proc, lambda byt: cls._handle_diff_line(byt, repo, index),
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/diff.py", line 517, in _handle_diff_line
    old_mode, new_mode, a_blob_id, b_blob_id, _change_type = meta.split(None, 4)
ValueError: not enough values to unpack (expected 5, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/cmd.py", line 120, in pump_stream
    raise CommandError([f'<{name}-pump>'] + remove_password_if_present(cmdline), ex) from ex
git.exc.CommandError: Cmd('<stdout-pump>') failed due to: ValueError('not enough values to unpack (expected 5, got 1)')
  cmdline: <stdout-pump> git diff-tree 528f1acd1af3b89853f50515c473167dc230d158 24125ba098550d3f1e7256a8cc536fd325d1ba20 -r --abbrev=40 --full-index -M --raw -z --no-color
Exception in thread Thread-87947:
Traceback (most recent call last):
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/cmd.py", line 114, in pump_stream
    handler(line)
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/diff.py", line 570, in <lambda>
    handle_process_output(proc, lambda byt: cls._handle_diff_line(byt, repo, index),
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/diff.py", line 517, in _handle_diff_line
    old_mode, new_mode, a_blob_id, b_blob_id, _change_type = meta.split(None, 4)
ValueError: not enough values to unpack (expected 5, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/bohrok/.pyenv/versions/3.9.7/lib/python3.9/site-packages/git/cmd.py", line 120, in pump_stream
    raise CommandError([f'<{name}-pump>'] + remove_password_if_present(cmdline), ex) from ex
git.exc.CommandError: Cmd('<stdout-pump>') failed due to: ValueError('not enough values to unpack (expected 5, got 1)')
  cmdline: <stdout-pump> git diff-tree 528f1acd1af3b89853f50515c473167dc230d158 24125ba098550d3f1e7256a8cc536fd325d1ba20 -r --abbrev=40 --full-index -M --raw -z --no-color
